name: Quality Checks Pack

on:
  workflow_call:
    inputs:
      run-lint:
        description: 'Run lint check'
        required: false
        default: true
        type: boolean
      run-typecheck:
        description: 'Run type check'
        required: false
        default: true
        type: boolean
      run-test:
        description: 'Run tests'
        required: false
        default: true
        type: boolean
      run-build:
        description: 'Run build'
        required: false
        default: false
        type: boolean
      run-security:
        description: 'Run security checks'
        required: false
        default: false
        type: boolean
      test-coverage:
        description: 'Run tests with coverage'
        required: false
        default: false
        type: boolean
      node-version:
        description: 'Node.js version'
        required: false
        default: '22'
        type: string
      pnpm-version:
        description: 'pnpm version'
        required: false
        default: '10.11.0'
        type: string
      working-directory:
        description: 'Working directory'
        required: false
        default: '.'
        type: string
      lint-command:
        description: 'Custom lint command'
        required: false
        default: 'pnpm lint'
        type: string
      typecheck-command:
        description: 'Custom type check command'
        required: false
        default: 'pnpm type-check'
        type: string
      test-command:
        description: 'Custom test command'
        required: false
        default: ''
        type: string
      build-command:
        description: 'Custom build command'
        required: false
        default: 'pnpm build'
        type: string

jobs:
  lint:
    if: inputs.run-lint
    uses: NextNodeSolutions/github-actions/workflows/jobs/lint.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}
      working-directory: ${{ inputs.working-directory }}
      command: ${{ inputs.lint-command }}
      
  typecheck:
    if: inputs.run-typecheck
    uses: NextNodeSolutions/github-actions/workflows/jobs/typecheck.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}
      working-directory: ${{ inputs.working-directory }}
      command: ${{ inputs.typecheck-command }}
      
  test:
    if: inputs.run-test
    uses: NextNodeSolutions/github-actions/workflows/jobs/test.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}
      working-directory: ${{ inputs.working-directory }}
      coverage: ${{ inputs.test-coverage }}
      command: ${{ inputs.test-command }}
      
  build:
    if: inputs.run-build
    uses: NextNodeSolutions/github-actions/workflows/jobs/build.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}
      working-directory: ${{ inputs.working-directory }}
      command: ${{ inputs.build-command }}
      
  security:
    if: inputs.run-security
    uses: NextNodeSolutions/github-actions/workflows/jobs/security.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}
      working-directory: ${{ inputs.working-directory }}