name: 'Setup Environment'
description: 'Complete environment setup for Node.js projects'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version'
    required: false
    default: '10.11.0'
  install-deps:
    description: 'Install dependencies'
    required: false
    default: 'true'
  frozen-lockfile:
    description: 'Use frozen lockfile'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml
        
    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.frozen-lockfile }}" == "true" ]; then
          pnpm install --frozen-lockfile
        else
          pnpm install
        fi