name: 'Changesets Version'
description: 'Handle versioning and PR creation for changesets release process'
author: 'NextNode'

inputs:
  github-token:
    description: 'GitHub token for changesets'
    required: true
  version-script:
    description: 'Script to run for versioning'
    required: false
    default: 'changeset:version'
  commit-message:
    description: 'Commit message for version changes'
    required: false
    default: 'Version packages'

outputs:
  has-changesets:
    description: 'Whether there are pending changesets'
    value: ${{ steps.check.outputs.has-changesets }}
  published:
    description: 'Whether packages were published'
    value: ${{ steps.version.outputs.published }}
  pr-created:
    description: 'Whether a version PR was created'
    value: ${{ steps.version.outputs.pr-created }}
  pr-number:
    description: 'Version PR number if created'
    value: ${{ steps.version.outputs.pr-number }}

runs:
  using: 'composite'
  steps:
    - name: Check for pending changesets
      id: check
      shell: bash
      run: |
        echo "::group::ðŸ” Checking for pending changesets"
        
        CHANGESET_COUNT=$(find .changeset -name "*.md" ! -name "README.md" | wc -l)
        
        if [ $CHANGESET_COUNT -gt 0 ]; then
          echo "âœ… Found $CHANGESET_COUNT pending changeset(s)"
          echo "has-changesets=true" >> $GITHUB_OUTPUT
          
          echo "ðŸ“‹ Pending changesets:"
          find .changeset -name "*.md" ! -name "README.md" -exec basename {} \;
        else
          echo "â„¹ï¸  No pending changesets found"
          echo "has-changesets=false" >> $GITHUB_OUTPUT
        fi
        
        echo "::endgroup::"

    - name: Run changesets version
      id: version
      shell: bash
      run: |
        echo "::group::ðŸ“¦ Running changesets version"
        
        # Set git configuration for changesets
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Run changesets version command
        echo "ðŸ”„ Running: pnpm run ${{ inputs.version-script }}"
        pnpm run ${{ inputs.version-script }}
        
        # Check if changesets made a version commit
        if ! git diff --quiet HEAD~1; then
          echo "âœ… Version changes detected"
          
          # Get new version
          VERSION=$(node -p "require('./package.json').version")
          
          # Amend commit with proper message and create tag
          git commit --amend -m "chore: updated to $VERSION"
          git tag "v$VERSION"
          
          # Push changes and tags
          echo "ðŸš€ Pushing changes and tags to origin/main"
          git push origin main --tags
          
          echo "published=true" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "â„¹ï¸ No version changes were made"
          echo "published=false" >> $GITHUB_OUTPUT
        fi
        
        echo "::endgroup::"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Display version summary
      if: steps.version.outputs.published == 'true'
      shell: bash
      run: |
        echo "::group::ðŸ“Š Version Summary"
        
        # Show what was changed in the last commit
        echo "ðŸ”„ Changes in version commit:"
        git show --stat HEAD
        
        # Show current package version
        if [[ -f "package.json" ]]; then
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "ðŸ“¦ $PACKAGE_NAME@$PACKAGE_VERSION"
        fi
        
        echo "::endgroup::"