name: 'Complete Node.js Setup'
description: 'Complete setup for Node.js projects including checkout, pnpm setup, and dependency installation'
author: 'NextNodeSolutions'

inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
  enable-cache:
    description: 'Enable dependency caching'
    required: false
    default: 'true'
  frozen-lockfile:
    description: 'Use frozen lockfile for installation'
    required: false
    default: 'true'
  checkout:
    description: 'Run checkout step'
    required: false
    default: 'true'
  install-dependencies:
    description: 'Install dependencies with pnpm'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      if: inputs.checkout == 'true'
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
        
    - name: Add pnpm to PATH
      shell: bash
      run: |
        echo "$(pnpm config get global-bin-dir)" >> $GITHUB_PATH
        echo "pnpm version: $(pnpm --version)"
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: ${{ inputs.enable-cache == 'true' && 'pnpm' || '' }}
        
    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      uses: NextNodeSolutions/github-actions/actions/build/install@main
      with:
        working-directory: ${{ inputs.working-directory }}
        frozen-lockfile: ${{ inputs.frozen-lockfile }}