name: 'Python Setup'
description: 'Setup Python with specified version and install pip packages'
author: 'NextNodeSolutions'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.11'
  packages:
    description: 'Comma-separated list of pip packages to install'
    required: false
    default: 'requests'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pip packages
      shell: bash
      env:
        PACKAGES: ${{ inputs.packages }}
      run: |
        echo "::group::Python Setup"
        echo "Python version: $(python --version)"

        if [ -n "$PACKAGES" ]; then
          PACKAGE_LIST=$(echo "$PACKAGES" | tr ',' ' ')
          echo "Installing packages: $PACKAGE_LIST"
          pip install --quiet $PACKAGE_LIST
          echo "Packages installed successfully"
        else
          echo "No packages to install"
        fi

        echo "::endgroup::"

    - name: Add shared lib to PYTHONPATH
      shell: bash
      run: |
        # Add lib to PYTHONPATH for shared modules
        # Check multiple possible locations based on how actions are used

        # When used via checkout of github-actions repo directly
        if [[ -d "$GITHUB_WORKSPACE/lib" ]]; then
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$PYTHONPATH" >> $GITHUB_ENV
          echo "Added workspace root to PYTHONPATH (lib/ found)"
        # When used via sparse checkout into .github-actions/
        elif [[ -d "$GITHUB_WORKSPACE/.github-actions/lib" ]]; then
          echo "PYTHONPATH=$GITHUB_WORKSPACE/.github-actions:$PYTHONPATH" >> $GITHUB_ENV
          echo "Added .github-actions to PYTHONPATH"
        # When running from action's own directory (internal testing)
        elif [[ -d "$GITHUB_ACTION_PATH/../../../lib" ]]; then
          LIB_PATH=$(cd "$GITHUB_ACTION_PATH/../../.." && pwd)
          echo "PYTHONPATH=$LIB_PATH:$PYTHONPATH" >> $GITHUB_ENV
          echo "Added action root to PYTHONPATH"
        fi
