name: 'Dokploy Deploy Trigger'
description: 'Trigger deployment on Dokploy application'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  app-id:
    description: 'Dokploy application ID'
    required: true

outputs:
  deployment-id:
    description: 'Dokploy deployment ID'
    value: ${{ steps.deploy.outputs.deployment-id }}
  triggered:
    description: 'Whether deployment was triggered successfully'
    value: ${{ steps.deploy.outputs.triggered }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.deploy.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: nextnodesolutions/github-actions/actions/utilities/python-setup@main
      with:
        packages: 'requests'

    - name: Trigger deployment
      id: deploy
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        APP_ID: ${{ inputs.app-id }}
      run: |
        import os
        import sys

        from lib.dokploy import DEPLOY_TIMEOUT, DokployClient, DokployError, Endpoints, output

        APP_ID = os.environ['APP_ID']

        print("::group::Triggering deployment")
        print(f"Application ID: {APP_ID}")

        try:
            client = DokployClient.from_env()

            result = client.post(
                Endpoints.APPLICATION_DEPLOY,
                json={"applicationId": APP_ID},
                timeout=DEPLOY_TIMEOUT
            )

            deployment_id = result.get('deploymentId', '')
            print("Deployment triggered successfully")
            output('deployment-id', deployment_id)
            output('triggered', 'true')
            output('success', 'true')

        except DokployError as e:
            print(f"::error::Failed to trigger deployment: {e}")
            output('deployment-id', '')
            output('triggered', 'false')
            output('success', 'false')
            sys.exit(1)

        print("::endgroup::")
