name: 'TypeScript Type Check'
description: 'Atomic action to run TypeScript type checking'
inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
  command:
    description: 'Type check command'
    required: false
    default: 'type-check'
  tsconfig-path:
    description: 'Path to tsconfig.json'
    required: false
    default: 'tsconfig.json'
  strict:
    description: 'Enforce strict mode'
    required: false
    default: 'true'

outputs:
  errors:
    description: 'Number of type errors'
    value: ${{ steps.typecheck.outputs.errors }}
  warnings:
    description: 'Number of warnings'
    value: ${{ steps.typecheck.outputs.warnings }}
  duration:
    description: 'Time taken'
    value: ${{ steps.typecheck.outputs.duration }}

runs:
  using: 'composite'
  steps:
    - name: Setup
      shell: bash
      env:
        INPUT_WORKING_DIR: ${{ inputs.working-directory }}
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_TSCONFIG: ${{ inputs.tsconfig-path }}
        INPUT_STRICT: ${{ inputs.strict }}
      run: |
        echo "::group::📝 TypeScript Type Check Setup"
        echo "• Working directory: $INPUT_WORKING_DIR"
        echo "• Command: pnpm $INPUT_COMMAND"
        echo "• Config: $INPUT_TSCONFIG"
        echo "• Strict mode: $INPUT_STRICT"
        echo "::endgroup::"

    - name: Verify TypeScript config
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INPUT_TSCONFIG: ${{ inputs.tsconfig-path }}
        INPUT_STRICT: ${{ inputs.strict }}
      run: |
        echo "::group::🔍 Verifying TypeScript Configuration"

        # Validate tsconfig path (no shell metacharacters)
        if [[ ! "$INPUT_TSCONFIG" =~ ^[a-zA-Z0-9_./-]+$ ]]; then
          echo "❌ Invalid tsconfig path: contains unsafe characters"
          exit 1
        fi

        # Check if tsconfig exists
        if [[ -f "$INPUT_TSCONFIG" ]]; then
          echo "✅ Found $INPUT_TSCONFIG"

          # Check strict mode setting
          if [[ "$INPUT_STRICT" == "true" ]]; then
            if grep -q '"strict":\s*true' "$INPUT_TSCONFIG"; then
              echo "✅ Strict mode is enabled"
            else
              echo "⚠️ Strict mode is not enabled in tsconfig"
            fi
          fi

          # Show compiler options
          echo "• Compiler options:"
          grep -A 10 '"compilerOptions"' "$INPUT_TSCONFIG" | head -15 || true
        else
          echo "❌ TypeScript config not found at $INPUT_TSCONFIG"
          exit 1
        fi

        echo "::endgroup::"

    - name: Run type check
      id: typecheck
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INPUT_COMMAND: ${{ inputs.command }}
      run: |
        echo "::group::🔧 Running Type Check"

        # Validate command (alphanumeric, dash, colon only - supports pnpm scripts like type-check)
        if [[ ! "$INPUT_COMMAND" =~ ^[a-zA-Z0-9_:-]+$ ]]; then
          echo "❌ Invalid command: contains unsafe characters"
          exit 1
        fi

        START_TIME=$(date +%s)

        # Run type check and capture output
        echo "• Executing: pnpm $INPUT_COMMAND"

        # Create temp file for output
        OUTPUT_FILE=$(mktemp)

        # Run command and capture output
        if pnpm "$INPUT_COMMAND" 2>&1 | tee "$OUTPUT_FILE"; then
          CHECK_STATUS="success"
          echo "✅ Type check passed"
        else
          CHECK_STATUS="failed"
          echo "❌ Type check failed"
        fi

        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        
        # Count errors and warnings
        ERROR_COUNT=$(grep -c "error TS" "$OUTPUT_FILE" 2>/dev/null || true)
        ERROR_COUNT=${ERROR_COUNT:-0}
        WARNING_COUNT=$(grep -c "warning" "$OUTPUT_FILE" 2>/dev/null || true)
        WARNING_COUNT=${WARNING_COUNT:-0}
        
        echo "• Errors found: $ERROR_COUNT"
        echo "• Warnings found: $WARNING_COUNT"
        echo "• Duration: ${DURATION}s"
        
        echo "errors=$ERROR_COUNT" >> $GITHUB_OUTPUT
        echo "warnings=$WARNING_COUNT" >> $GITHUB_OUTPUT
        echo "duration=${DURATION}s" >> $GITHUB_OUTPUT
        
        # Clean up
        rm -f "$OUTPUT_FILE"
        
        echo "::endgroup::"
        
        # Fail if errors found
        if [[ "$CHECK_STATUS" == "failed" ]]; then
          exit 1
        fi

    - name: Type check summary
      if: always()
      shell: bash
      run: |
        echo "::group::📊 Type Check Summary"
        echo "• Errors: ${{ steps.typecheck.outputs.errors }}"
        echo "• Warnings: ${{ steps.typecheck.outputs.warnings }}"
        echo "• Duration: ${{ steps.typecheck.outputs.duration }}"
        
        if [[ "${{ steps.typecheck.outputs.errors }}" == "0" ]]; then
          echo "✅ No type errors found"
        else
          echo "❌ Fix ${{ steps.typecheck.outputs.errors }} type error(s) before proceeding"
        fi
        
        echo "::endgroup::"