name: 'Dokploy Project Sync'
description: 'Create or get Dokploy project'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  project-name:
    description: 'Project name'
    required: true
  project-description:
    description: 'Project description'
    required: false
    default: ''

outputs:
  project-id:
    description: 'Dokploy project ID'
    value: ${{ steps.sync.outputs.project-id }}
  created:
    description: 'Whether project was created (true) or already existed (false)'
    value: ${{ steps.sync.outputs.created }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.sync.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: nextnodesolutions/github-actions/actions/utilities/python-setup@main
      with:
        packages: 'requests'

    - name: Sync project
      id: sync
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        PROJECT_NAME: ${{ inputs.project-name }}
        PROJECT_DESCRIPTION: ${{ inputs.project-description }}
      run: |
        import os
        import sys

        from lib.dokploy import DokployClient, DokployError, Endpoints, output

        PROJECT_NAME = os.environ['PROJECT_NAME']
        PROJECT_DESCRIPTION = os.environ.get('PROJECT_DESCRIPTION', '')

        print("::group::Syncing Dokploy project")

        try:
            client = DokployClient.from_env()

            # Get all projects
            projects = client.get(Endpoints.PROJECT_ALL, raise_for_status=False)
            if not isinstance(projects, list):
                projects = []

            # Find existing project
            for p in projects:
                if p.get('name') == PROJECT_NAME:
                    project_id = p.get('projectId')
                    print(f"Found existing project: {PROJECT_NAME} ({project_id})")
                    output('project-id', project_id)
                    output('created', 'false')
                    output('success', 'true')
                    print("::endgroup::")
                    sys.exit(0)

            # Create project
            create_data = client.post(
                Endpoints.PROJECT_CREATE,
                json={"name": PROJECT_NAME, "description": PROJECT_DESCRIPTION}
            )

            project_id = create_data.get('projectId') or create_data.get('id')

            if not project_id:
                # Fallback: search again
                projects = client.get(Endpoints.PROJECT_ALL, raise_for_status=False)
                if isinstance(projects, list):
                    for p in projects:
                        if p.get('name') == PROJECT_NAME:
                            project_id = p.get('projectId')
                            break

            if not project_id:
                print("::error::Failed to get project ID after creation")
                output('success', 'false')
                sys.exit(1)

            print(f"Created project: {PROJECT_NAME} ({project_id})")
            output('project-id', project_id)
            output('created', 'true')
            output('success', 'true')

        except DokployError as e:
            print(f"::error::Failed to sync project: {e}")
            output('success', 'false')
            sys.exit(1)

        print("::endgroup::")
