name: 'Dokploy Environment Sync'
description: 'Create or get Dokploy environment within a project'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  project-id:
    description: 'Dokploy project ID'
    required: true
  environment:
    description: 'Target environment name'
    required: true
  pr-number:
    description: 'PR number (for preview environments)'
    required: false
    default: ''

outputs:
  environment-id:
    description: 'Dokploy environment ID'
    value: ${{ steps.sync.outputs.environment-id }}
  environment-name:
    description: 'Environment name used'
    value: ${{ steps.sync.outputs.environment-name }}
  created:
    description: 'Whether environment was created (true) or already existed (false)'
    value: ${{ steps.sync.outputs.created }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.sync.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: nextnodesolutions/github-actions/actions/utilities/python-setup@main
      with:
        packages: 'requests'

    - name: Sync environment
      id: sync
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        PROJECT_ID: ${{ inputs.project-id }}
        ENVIRONMENT: ${{ inputs.environment }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        import os
        import sys

        from lib.dokploy import DokployClient, DokployError, Endpoints, output

        PROJECT_ID = os.environ['PROJECT_ID']
        ENVIRONMENT = os.environ['ENVIRONMENT']
        PR_NUMBER = os.environ.get('PR_NUMBER', '')

        # Compute environment name
        if ENVIRONMENT == 'preview' and PR_NUMBER:
            env_name = f"preview-{PR_NUMBER}"
        else:
            env_name = ENVIRONMENT

        print("::group::Syncing Dokploy environment")
        print(f"Environment name: {env_name}")

        try:
            client = DokployClient.from_env()

            # Get project details to find environments
            project_data = client.get(
                Endpoints.PROJECT_ONE,
                params={"projectId": PROJECT_ID},
                raise_for_status=False
            )
            if not isinstance(project_data, dict):
                project_data = {}
            environments = project_data.get('environments', [])

            # Find existing environment
            for env in environments:
                if env.get('name') == env_name:
                    environment_id = env.get('environmentId')
                    print(f"Found existing environment: {env_name} ({environment_id})")
                    output('environment-id', environment_id)
                    output('environment-name', env_name)
                    output('created', 'false')
                    output('success', 'true')
                    print("::endgroup::")
                    sys.exit(0)

            # Create environment
            create_data = client.post(
                Endpoints.ENVIRONMENT_CREATE,
                json={
                    "projectId": PROJECT_ID,
                    "name": env_name,
                    "description": f"Environment for {env_name}"
                }
            )
            environment_id = create_data.get('environmentId')
            print(f"Created environment: {env_name} ({environment_id})")
            output('environment-id', environment_id)
            output('environment-name', env_name)
            output('created', 'true')
            output('success', 'true')

        except DokployError as e:
            print(f"::error::Failed to sync environment: {e}")
            output('success', 'false')
            sys.exit(1)

        print("::endgroup::")
