name: 'Dokploy Environment Sync'
description: 'Create or get Dokploy environment within a project'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  project-id:
    description: 'Dokploy project ID'
    required: true
  environment:
    description: 'Target environment name'
    required: true
  pr-number:
    description: 'PR number (for preview environments)'
    required: false
    default: ''

outputs:
  environment-id:
    description: 'Dokploy environment ID'
    value: ${{ steps.sync.outputs.environment-id }}
  environment-name:
    description: 'Environment name used'
    value: ${{ steps.sync.outputs.environment-name }}
  created:
    description: 'Whether environment was created (true) or already existed (false)'
    value: ${{ steps.sync.outputs.created }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.sync.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install requests

    - name: Sync environment
      id: sync
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        PROJECT_ID: ${{ inputs.project-id }}
        ENVIRONMENT: ${{ inputs.environment }}
        PR_NUMBER: ${{ inputs.pr-number }}
        GITHUB_OUTPUT: ${{ github.output }}
      run: |
        import os
        import sys
        import requests

        DOKPLOY_URL = os.environ['DOKPLOY_URL'].rstrip('/')
        DOKPLOY_TOKEN = os.environ['DOKPLOY_TOKEN']
        PROJECT_ID = os.environ['PROJECT_ID']
        ENVIRONMENT = os.environ['ENVIRONMENT']
        PR_NUMBER = os.environ.get('PR_NUMBER', '')
        GITHUB_OUTPUT = os.environ.get('GITHUB_OUTPUT', '')

        def output(key, value):
            if GITHUB_OUTPUT:
                with open(GITHUB_OUTPUT, 'a') as f:
                    f.write(f"{key}={value}\n")

        headers = {
            "Authorization": f"Bearer {DOKPLOY_TOKEN}",
            "Content-Type": "application/json"
        }

        # Compute environment name
        if ENVIRONMENT == 'preview' and PR_NUMBER:
            env_name = f"preview-{PR_NUMBER}"
        else:
            env_name = ENVIRONMENT

        print("::group::Syncing Dokploy environment")
        print(f"Environment name: {env_name}")

        try:
            # Get project details to find environments
            project_resp = requests.get(
                f"{DOKPLOY_URL}/api/project.one",
                params={"projectId": PROJECT_ID},
                headers=headers,
                timeout=30
            )
            project_data = project_resp.json() if project_resp.ok else {}
            environments = project_data.get('environments', [])

            # Find existing environment
            environment_id = None
            for env in environments:
                if env.get('name') == env_name:
                    environment_id = env.get('environmentId')
                    print(f"Found existing environment: {env_name} ({environment_id})")
                    output('environment-id', environment_id)
                    output('environment-name', env_name)
                    output('created', 'false')
                    output('success', 'true')
                    print("::endgroup::")
                    sys.exit(0)

            # Create environment
            create_resp = requests.post(
                f"{DOKPLOY_URL}/api/environment.create",
                headers=headers,
                json={
                    "projectId": PROJECT_ID,
                    "name": env_name,
                    "description": f"Environment for {env_name}"
                },
                timeout=30
            )

            if create_resp.ok:
                environment_id = create_resp.json().get('environmentId')
                print(f"Created environment: {env_name} ({environment_id})")
                output('environment-id', environment_id)
                output('environment-name', env_name)
                output('created', 'true')
                output('success', 'true')
            else:
                # Fallback: use first available environment
                if environments:
                    environment_id = environments[0].get('environmentId')
                    env_name = environments[0].get('name', env_name)
                    print(f"Using default environment: {env_name} ({environment_id})")
                    output('environment-id', environment_id)
                    output('environment-name', env_name)
                    output('created', 'false')
                    output('success', 'true')
                else:
                    print(f"::error::Failed to create environment: {create_resp.text}")
                    output('success', 'false')
                    sys.exit(1)

        except Exception as e:
            print(f"::error::Failed to sync environment: {e}")
            output('success', 'false')
            sys.exit(1)

        print("::endgroup::")
