name: 'Dokploy App Create'
description: 'Create or find existing Dokploy application'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  project-id:
    description: 'Dokploy project ID'
    required: true
  environment-id:
    description: 'Dokploy environment ID'
    required: true
  app-name:
    description: 'Application name'
    required: true
  description:
    description: 'Application description'
    required: false
    default: ''
  server-id:
    description: 'Dokploy server ID'
    required: false
    default: ''
  build-type:
    description: 'Build type (dockerfile, nixpacks, etc.)'
    required: false
    default: 'dockerfile'

outputs:
  app-id:
    description: 'Dokploy application ID'
    value: ${{ steps.create.outputs.app-id }}
  created:
    description: 'Whether application was created (true) or already existed (false)'
    value: ${{ steps.create.outputs.created }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.create.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install requests

    - name: Create or find application
      id: create
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        PROJECT_ID: ${{ inputs.project-id }}
        ENVIRONMENT_ID: ${{ inputs.environment-id }}
        APP_NAME: ${{ inputs.app-name }}
        DESCRIPTION: ${{ inputs.description }}
        SERVER_ID: ${{ inputs.server-id }}
        BUILD_TYPE: ${{ inputs.build-type }}
        GITHUB_OUTPUT: ${{ github.output }}
      run: |
        import os
        import sys
        import requests

        DOKPLOY_URL = os.environ['DOKPLOY_URL'].rstrip('/')
        DOKPLOY_TOKEN = os.environ['DOKPLOY_TOKEN']
        PROJECT_ID = os.environ['PROJECT_ID']
        ENVIRONMENT_ID = os.environ['ENVIRONMENT_ID']
        APP_NAME = os.environ['APP_NAME']
        DESCRIPTION = os.environ.get('DESCRIPTION', '')
        SERVER_ID = os.environ.get('SERVER_ID', '')
        BUILD_TYPE = os.environ.get('BUILD_TYPE', 'dockerfile')
        GITHUB_OUTPUT = os.environ.get('GITHUB_OUTPUT', '')

        def output(key, value):
            if GITHUB_OUTPUT:
                with open(GITHUB_OUTPUT, 'a') as f:
                    f.write(f"{key}={value}\n")

        headers = {
            "Authorization": f"Bearer {DOKPLOY_TOKEN}",
            "Content-Type": "application/json"
        }

        print("::group::Creating/finding Dokploy application")
        print(f"Application: {APP_NAME}")

        try:
            # Get project details to find existing apps
            project_resp = requests.get(
                f"{DOKPLOY_URL}/api/project.one",
                params={"projectId": PROJECT_ID},
                headers=headers,
                timeout=30
            )

            apps = []
            if project_resp.ok:
                project_detail = project_resp.json()
                for env in project_detail.get('environments', []):
                    apps.extend(env.get('applications', []))

            # Find existing app
            app_id = None
            for a in apps:
                if a.get('name') == APP_NAME:
                    app_id = a.get('applicationId')
                    print(f"Found existing application: {APP_NAME} ({app_id})")
                    output('app-id', app_id)
                    output('created', 'false')
                    output('success', 'true')
                    print("::endgroup::")
                    sys.exit(0)

            # Create application
            app_data = {
                "name": APP_NAME,
                "projectId": PROJECT_ID,
                "environmentId": ENVIRONMENT_ID,
                "buildType": BUILD_TYPE,
            }
            if DESCRIPTION:
                app_data["description"] = DESCRIPTION
            if SERVER_ID:
                app_data["serverId"] = SERVER_ID

            create_resp = requests.post(
                f"{DOKPLOY_URL}/api/application.create",
                headers=headers,
                json=app_data,
                timeout=30
            )
            create_resp.raise_for_status()
            app_id = create_resp.json().get('applicationId')

            print(f"Created application: {APP_NAME} ({app_id})")
            output('app-id', app_id)
            output('created', 'true')
            output('success', 'true')

        except Exception as e:
            print(f"::error::Failed to create application: {e}")
            output('success', 'false')
            sys.exit(1)

        print("::endgroup::")
