packer {
  required_plugins {
    hcloud = {
      source  = "github.com/hetznercloud/hcloud"
      version = ">= 1.4.0"
    }
  }
}

variable "hcloud_token" {
  type      = string
  sensitive = true
}

variable "location" {
  type        = string
  description = "Hetzner datacenter location (from infrastructure/config.json via workflow)"
}

source "hcloud" "nixos" {
  token        = var.hcloud_token
  image        = "ubuntu-24.04"
  location     = var.location
  server_type  = "cx23"
  ssh_username = "root"
  snapshot_name = "nixos-dokploy-${formatdate("YYYYMMDD-hhmmss", timestamp())}"
  snapshot_labels = {
    type       = "nixos-dokploy"
    managed_by = "packer"
  }
}

build {
  sources = ["source.hcloud.nixos"]

  # Step 1: Prepare Ubuntu
  provisioner "shell" {
    inline_shebang = "/bin/bash -e"
    inline = [
      "apt-get update",
      "apt-get install -y curl git"
    ]
  }

  # Step 2: Upload our NixOS flake configuration to a temp location
  # We upload BEFORE nixos-infect so files are available, but NOT to /etc/nixos
  # to avoid nixos-infect detecting and mishandling our configuration.nix
  provisioner "shell" {
    inline_shebang = "/bin/bash -e"
    inline = [
      "mkdir -p /tmp/nixos-config"
    ]
  }

  provisioner "file" {
    source      = "files/"
    destination = "/tmp/nixos-config"
  }

  # Step 3: Run nixos-infect to convert Ubuntu to NixOS (minimal config)
  # NO_REBOOT=1 prevents automatic reboot so we can configure further
  provisioner "shell" {
    inline_shebang = "/bin/bash -e"
    environment_vars = [
      "NIX_CHANNEL=nixos-24.11",
      "NO_REBOOT=1"
    ]
    inline = [
      "curl -L https://github.com/elitak/nixos-infect/raw/master/nixos-infect | bash -x"
    ]
  }

  # Step 4: Replace nixos-infect's minimal config with our flake configuration
  # and prepare the system with Dokploy for next boot
  provisioner "shell" {
    inline_shebang = "/bin/bash -e"
    inline = [
      "source /root/.nix-profile/etc/profile.d/nix.sh",
      "# Verify uploaded files structure",
      "echo '=== Uploaded NixOS config structure ==='",
      "find /tmp/nixos-config -type f -name '*.nix' | head -20",
      "# Keep the hardware-configuration.nix generated by nixos-infect",
      "cp /etc/nixos/hardware-configuration.nix /tmp/nixos-config/",
      "# Replace /etc/nixos with our flake configuration",
      "rm -rf /etc/nixos/*",
      "cp -r /tmp/nixos-config/* /etc/nixos/",
      "# Verify final structure",
      "echo '=== Final /etc/nixos structure ==='",
      "find /etc/nixos -type f -name '*.nix'",
      "# Enable flakes",
      "mkdir -p ~/.config/nix",
      "echo 'experimental-features = nix-command flakes' > ~/.config/nix/nix.conf",
      "# Update flake inputs and build",
      "cd /etc/nixos",
      "nix flake update",
      "# Use nixos-rebuild boot since we're not running NixOS yet (NO_REBOOT=1 from nixos-infect)",
      "# 'boot' prepares the configuration for next boot without activating now",
      "nix-env -iA nixos.nixos-rebuild",
      "nixos-rebuild boot --flake .#dokploy-server"
    ]
  }

  # Step 5: Clean up to minimize snapshot size
  provisioner "shell" {
    inline_shebang = "/bin/bash -e"
    inline = [
      "source /root/.nix-profile/etc/profile.d/nix.sh || source /etc/profile.d/nix.sh || true",
      "nix-collect-garbage -d || true",
      "rm -rf /root/.cache",
      "rm -rf /tmp/*",
      "sync"
    ]
  }
}
