"""Health check constants."""

DEFAULT_HEALTH_PATH = "/health"
DEFAULT_HEALTH_INTERVAL = 30
DEFAULT_HEALTH_TIMEOUT = 10
DEFAULT_HEALTH_RETRIES = 3
DEFAULT_HEALTH_START_PERIOD = 40
HEALTH_SUCCESS_CODES = "200,201,204,301,302"
