name: 'Tailscale Device Cleanup'
description: 'Delete Tailscale devices matching hostname patterns'
author: 'NextNodeSolutions'

inputs:
  tailscale-api-key:
    description: 'Tailscale API key with device management permissions'
    required: true
  target:
    description: 'Target pattern: all, admin-dokploy, dev-worker, prod-worker, or custom comma-separated patterns'
    required: true
    default: 'all'

outputs:
  devices-deleted:
    description: 'Number of devices deleted'
    value: ${{ steps.cleanup.outputs.devices-deleted }}
  deleted-hostnames:
    description: 'Comma-separated list of deleted hostnames'
    value: ${{ steps.cleanup.outputs.deleted-hostnames }}

runs:
  using: 'composite'
  steps:
    - name: Delete Tailscale Devices
      id: cleanup
      shell: bash
      env:
        TAILSCALE_API_KEY: ${{ inputs.tailscale-api-key }}
        INPUT_TARGET: ${{ inputs.target }}
      run: |
        echo "::group::Delete Tailscale devices for target: $INPUT_TARGET"

        DEVICES_DELETED=0
        DELETED_HOSTNAMES=""

        # Get all devices from Tailscale
        DEVICES=$(curl -s -H "Authorization: Bearer ${TAILSCALE_API_KEY}" \
          "https://api.tailscale.com/api/v2/tailnet/-/devices")

        if ! echo "$DEVICES" | jq -e '.devices' > /dev/null 2>&1; then
          echo "::error::Failed to fetch devices from Tailscale API"
          echo "devices-deleted=0" >> $GITHUB_OUTPUT
          echo "deleted-hostnames=" >> $GITHUB_OUTPUT
          echo "::endgroup::"
          exit 1
        fi

        # Define hostnames to delete based on target
        case "$INPUT_TARGET" in
          "all")
            PATTERNS="admin-dokploy dev-worker prod-worker"
            ;;
          "admin-dokploy")
            PATTERNS="admin-dokploy"
            ;;
          "dev-worker")
            PATTERNS="dev-worker"
            ;;
          "prod-worker")
            PATTERNS="prod-worker"
            ;;
          *)
            # Custom comma-separated patterns
            PATTERNS=$(echo "$INPUT_TARGET" | tr ',' ' ')
            ;;
        esac

        echo "Searching for devices matching patterns: $PATTERNS"
        echo ""

        # Delete matching devices (including -1, -2 suffixes)
        for pattern in $PATTERNS; do
          # Validate pattern (alphanumeric, dash, underscore only)
          if [[ ! "$pattern" =~ ^[a-zA-Z0-9_-]+$ ]]; then
            echo "::warning::Skipping invalid pattern: $pattern"
            continue
          fi

          DEVICE_IDS=$(echo "$DEVICES" | jq -r ".devices[] | select(.hostname | startswith(\"$pattern\")) | .id")

          for device_id in $DEVICE_IDS; do
            if [ -n "$device_id" ] && [ "$device_id" != "null" ]; then
              HOSTNAME=$(echo "$DEVICES" | jq -r ".devices[] | select(.id == \"$device_id\") | .hostname")
              echo "Deleting Tailscale device: $HOSTNAME ($device_id)"

              DELETE_RESPONSE=$(curl -s -w "%{http_code}" -o /dev/null -X DELETE \
                -H "Authorization: Bearer ${TAILSCALE_API_KEY}" \
                "https://api.tailscale.com/api/v2/device/${device_id}")

              if [ "$DELETE_RESPONSE" = "200" ] || [ "$DELETE_RESPONSE" = "204" ]; then
                echo "  Deleted successfully"
                DEVICES_DELETED=$((DEVICES_DELETED + 1))
                if [ -n "$DELETED_HOSTNAMES" ]; then
                  DELETED_HOSTNAMES="$DELETED_HOSTNAMES,$HOSTNAME"
                else
                  DELETED_HOSTNAMES="$HOSTNAME"
                fi
              else
                echo "::warning::Failed to delete device $HOSTNAME (HTTP $DELETE_RESPONSE)"
              fi
            fi
          done
        done

        echo ""
        echo "Cleanup Summary:"
        echo "  Devices deleted: $DEVICES_DELETED"
        if [ -n "$DELETED_HOSTNAMES" ]; then
          echo "  Hostnames: $DELETED_HOSTNAMES"
        fi

        echo "devices-deleted=$DEVICES_DELETED" >> $GITHUB_OUTPUT
        echo "deleted-hostnames=$DELETED_HOSTNAMES" >> $GITHUB_OUTPUT

        echo "::endgroup::"
