name: 'Dokploy Health Config'
description: 'Configure health check on Dokploy application'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  app-id:
    description: 'Dokploy application ID'
    required: true
  port:
    description: 'Application port'
    required: false
    default: '3000'
  health-path:
    description: 'Health check endpoint path'
    required: false
    default: '/health'
  health-interval:
    description: 'Health check interval in seconds'
    required: false
    default: '30'
  health-timeout:
    description: 'Health check timeout in seconds'
    required: false
    default: '10'
  health-retries:
    description: 'Health check retries'
    required: false
    default: '3'
  health-start-period:
    description: 'Health check start period in seconds'
    required: false
    default: '40'
  rollback-on-failure:
    description: 'Auto-rollback on deployment failure'
    required: false
    default: 'true'

outputs:
  configured:
    description: 'Whether health check was configured successfully'
    value: ${{ steps.config.outputs.configured }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.config.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: nextnodesolutions/github-actions/actions/utilities/python-setup@main
      with:
        packages: 'requests'

    - name: Configure health check
      id: config
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        APP_ID: ${{ inputs.app-id }}
        PORT: ${{ inputs.port }}
        HEALTH_PATH: ${{ inputs.health-path }}
        HEALTH_INTERVAL: ${{ inputs.health-interval }}
        HEALTH_TIMEOUT: ${{ inputs.health-timeout }}
        HEALTH_RETRIES: ${{ inputs.health-retries }}
        HEALTH_START_PERIOD: ${{ inputs.health-start-period }}
        ROLLBACK_ON_FAILURE: ${{ inputs.rollback-on-failure }}
      run: |
        import os
        import sys

        from lib.dokploy import (
            DEFAULT_HEALTH_INTERVAL,
            DEFAULT_HEALTH_PATH,
            DEFAULT_HEALTH_RETRIES,
            DEFAULT_HEALTH_START_PERIOD,
            DEFAULT_HEALTH_TIMEOUT,
            DEFAULT_APP_PORT,
            DokployClient,
            DokployError,
            Endpoints,
            output,
        )

        APP_ID = os.environ['APP_ID']
        PORT = int(os.environ.get('PORT', str(DEFAULT_APP_PORT)))
        HEALTH_PATH = os.environ.get('HEALTH_PATH', DEFAULT_HEALTH_PATH)
        HEALTH_INTERVAL = int(os.environ.get('HEALTH_INTERVAL', str(DEFAULT_HEALTH_INTERVAL)))
        HEALTH_TIMEOUT = int(os.environ.get('HEALTH_TIMEOUT', str(DEFAULT_HEALTH_TIMEOUT)))
        HEALTH_RETRIES = int(os.environ.get('HEALTH_RETRIES', str(DEFAULT_HEALTH_RETRIES)))
        HEALTH_START_PERIOD = int(os.environ.get('HEALTH_START_PERIOD', str(DEFAULT_HEALTH_START_PERIOD)))
        ROLLBACK = os.environ.get('ROLLBACK_ON_FAILURE', 'true').lower() == 'true'

        print("::group::Configuring health check")
        print(f"Health path: {HEALTH_PATH}")

        try:
            client = DokployClient.from_env()

            # Docker Swarm format for health check (nanoseconds)
            NANOSECONDS = 1_000_000_000

            # Use wget instead of curl - more commonly available in Alpine-based images
            # Use 127.0.0.1 instead of localhost - some Alpine images have DNS resolution issues
            healthcheck_swarm = {
                "Test": ["CMD", "wget", "-q", "-O", "/dev/null", f"http://127.0.0.1:{PORT}{HEALTH_PATH}"],
                "Interval": HEALTH_INTERVAL * NANOSECONDS,
                "Timeout": HEALTH_TIMEOUT * NANOSECONDS,
                "StartPeriod": HEALTH_START_PERIOD * NANOSECONDS,
                "Retries": HEALTH_RETRIES
            }

            update_config_swarm = {
                "Parallelism": 1,
                "Delay": 10 * NANOSECONDS,
                "FailureAction": "rollback" if ROLLBACK else "pause",
                "Order": "start-first"
            }

            client.post(
                Endpoints.APPLICATION_UPDATE,
                json={
                    "applicationId": APP_ID,
                    "healthCheckSwarm": healthcheck_swarm,
                    "updateConfigSwarm": update_config_swarm,
                }
            )

            print(f"Health check configured: {HEALTH_PATH}")
            output('configured', 'true')
            output('success', 'true')

        except DokployError as e:
            print(f"::error::Failed to configure health check: {e}")
            output('configured', 'false')
            output('success', 'false')
            sys.exit(1)

        print("::endgroup::")
