name: 'Dokploy Source Config'
description: 'Configure Docker or GitHub source for Dokploy application'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  app-id:
    description: 'Dokploy application ID'
    required: true
  source-type:
    description: 'Source type (docker or github)'
    required: true
  docker-image:
    description: 'Docker image (required if source-type is docker)'
    required: false
    default: ''
  github-url:
    description: 'GitHub repository URL (required if source-type is github)'
    required: false
    default: ''
  github-branch:
    description: 'GitHub branch'
    required: false
    default: 'main'
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'

outputs:
  configured:
    description: 'Whether source was configured successfully'
    value: ${{ steps.config.outputs.configured }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.config.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install requests

    - name: Configure source
      id: config
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        APP_ID: ${{ inputs.app-id }}
        SOURCE_TYPE: ${{ inputs.source-type }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        GITHUB_URL: ${{ inputs.github-url }}
        GITHUB_BRANCH: ${{ inputs.github-branch }}
        DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
        GITHUB_OUTPUT: ${{ github.output }}
      run: |
        import os
        import sys
        import requests

        DOKPLOY_URL = os.environ['DOKPLOY_URL'].rstrip('/')
        DOKPLOY_TOKEN = os.environ['DOKPLOY_TOKEN']
        APP_ID = os.environ['APP_ID']
        SOURCE_TYPE = os.environ['SOURCE_TYPE']
        DOCKER_IMAGE = os.environ.get('DOCKER_IMAGE', '')
        GITHUB_URL = os.environ.get('GITHUB_URL', '')
        GITHUB_BRANCH = os.environ.get('GITHUB_BRANCH', 'main')
        DOCKERFILE_PATH = os.environ.get('DOCKERFILE_PATH', './Dockerfile')
        GITHUB_OUTPUT = os.environ.get('GITHUB_OUTPUT', '')

        def output(key, value):
            if GITHUB_OUTPUT:
                with open(GITHUB_OUTPUT, 'a') as f:
                    f.write(f"{key}={value}\n")

        headers = {
            "Authorization": f"Bearer {DOKPLOY_TOKEN}",
            "Content-Type": "application/json"
        }

        print("::group::Configuring source")
        print(f"Source type: {SOURCE_TYPE}")

        try:
            if SOURCE_TYPE == 'docker':
                if not DOCKER_IMAGE:
                    print("::error::Docker image required for docker source type")
                    output('configured', 'false')
                    output('success', 'false')
                    sys.exit(1)

                print(f"Configuring Docker source: {DOCKER_IMAGE}")
                resp = requests.post(
                    f"{DOKPLOY_URL}/api/application.update",
                    headers=headers,
                    json={
                        "applicationId": APP_ID,
                        "sourceType": "docker",
                        "dockerImage": DOCKER_IMAGE,
                    },
                    timeout=30
                )

            elif SOURCE_TYPE == 'github':
                if not GITHUB_URL:
                    print("::error::GitHub URL required for github source type")
                    output('configured', 'false')
                    output('success', 'false')
                    sys.exit(1)

                print(f"Configuring GitHub source: {GITHUB_URL}")
                resp = requests.post(
                    f"{DOKPLOY_URL}/api/application.update",
                    headers=headers,
                    json={
                        "applicationId": APP_ID,
                        "sourceType": "github",
                        "customGitUrl": GITHUB_URL,
                        "customGitBranch": GITHUB_BRANCH,
                        "dockerfilePath": DOCKERFILE_PATH,
                    },
                    timeout=30
                )

            else:
                print(f"::error::Invalid source type: {SOURCE_TYPE}")
                output('configured', 'false')
                output('success', 'false')
                sys.exit(1)

            if resp.ok:
                print("Source configured successfully")
                output('configured', 'true')
                output('success', 'true')
            else:
                print(f"::warning::Source config failed: {resp.status_code} - {resp.text}")
                output('configured', 'false')
                output('success', 'false')

        except Exception as e:
            print(f"::error::Failed to configure source: {e}")
            output('configured', 'false')
            output('success', 'false')
            sys.exit(1)

        print("::endgroup::")
