name: 'Setup pnpm'
description: 'Setup pnpm package manager'
inputs:
  version:
    description: 'pnpm version to install'
    required: false
    default: '10.11.0'
  install-deps:
    description: 'Install dependencies after setup'
    required: false
    default: 'true'
  frozen-lockfile:
    description: 'Use frozen lockfile for installation'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.version }}
    
    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        if [ "${{ inputs.frozen-lockfile }}" == "true" ]; then
          pnpm install --frozen-lockfile
        else
          pnpm install
        fi