name: 'Dokploy Initialize'
description: 'Auto-setup Dokploy: create admin account (first-time), configure registry, import SSH keys. NOTE: Run docker-layer-repair BEFORE waiting for Dokploy to ensure images are healthy.'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL (e.g., https://admin.nextnode.fr)'
    required: true
  dokploy-admin-email:
    description: 'Dokploy admin email (for first-time setup only)'
    required: true
  dokploy-admin-password:
    description: 'Dokploy admin password (for first-time setup only)'
    required: true
  dokploy-ssh-private-key:
    description: 'SSH private key to import into Dokploy for worker access'
    required: true

outputs:
  success:
    description: 'Whether initialization succeeded'
    value: ${{ steps.result.outputs.success }}
  initialized-workers:
    description: 'Comma-separated list of initialized workers'
    value: ${{ steps.result.outputs.initialized-workers }}
  first-time-setup:
    description: 'Whether this was first-time Dokploy setup'
    value: ${{ steps.admin-setup.outputs.setup-completed }}

runs:
  using: 'composite'
  steps:
    # SEC-002: Mask pass-through secrets at parent level
    # This ensures secrets are masked before being passed to child actions
    - name: Mask Sensitive Inputs
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.dokploy-admin-password }}"
        echo "::add-mask::${{ inputs.dokploy-ssh-private-key }}"

    # Step 1: Admin setup (waits for Dokploy, creates admin if first time)
    # NOTE: docker-layer-repair action should be run BEFORE this action
    - name: Setup Dokploy Admin
      id: admin-setup
      uses: nextnodesolutions/github-actions/actions/infrastructure/dokploy-admin-setup@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        admin-email: ${{ inputs.dokploy-admin-email }}
        admin-password: ${{ inputs.dokploy-admin-password }}

    # Step 2: Authenticate with session cookies (for legacy sub-actions)
    - name: Authenticate with Dokploy (Session)
      id: auth
      shell: bash
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        ADMIN_EMAIL: ${{ inputs.dokploy-admin-email }}
        ADMIN_PASSWORD: ${{ inputs.dokploy-admin-password }}
      run: |
        echo "::group::Dokploy Session Authentication"

        # SEC-002: Ensure password is masked
        echo "::add-mask::${ADMIN_PASSWORD}"

        COOKIE_JAR="/tmp/dokploy_cookies_$$.txt"
        echo "cookie-jar=$COOKIE_JAR" >> $GITHUB_OUTPUT

        LOGIN_RESPONSE=$(curl -s -c "$COOKIE_JAR" -X POST "${DOKPLOY_URL}/api/auth/sign-in/email" \
          -H "Content-Type: application/json" \
          -d "{\"email\": \"${ADMIN_EMAIL}\", \"password\": \"${ADMIN_PASSWORD}\"}")

        if ! echo "$LOGIN_RESPONSE" | jq -e '.token' > /dev/null 2>&1; then
          echo "::error::Failed to authenticate with Dokploy"
          echo "success=false" >> $GITHUB_OUTPUT
          echo "::endgroup::"
          exit 1
        fi

        echo "Authentication successful"

        # Get organization ID
        ORGANIZATION_ID=$(echo "$LOGIN_RESPONSE" | jq -r '.user.activeOrganizationId // empty')
        if [[ -z "$ORGANIZATION_ID" ]]; then
          ORGANIZATION_ID=$(echo "$LOGIN_RESPONSE" | jq -r '.user.organizationId // empty')
        fi
        if [[ -z "$ORGANIZATION_ID" ]]; then
          SESSION_RESPONSE=$(curl -s -b "$COOKIE_JAR" "${DOKPLOY_URL}/api/auth/get-session")
          ORGANIZATION_ID=$(echo "$SESSION_RESPONSE" | jq -r '.session.activeOrganizationId // .user.activeOrganizationId // empty')
        fi
        if [[ -z "$ORGANIZATION_ID" ]]; then
          ORG_RESPONSE=$(curl -s -b "$COOKIE_JAR" "${DOKPLOY_URL}/api/organization.all")
          ORGANIZATION_ID=$(echo "$ORG_RESPONSE" | jq -r '.[0].organizationId // .[0].id // empty')
        fi

        if [[ -z "$ORGANIZATION_ID" ]]; then
          echo "::error::Could not get organization ID"
          echo "success=false" >> $GITHUB_OUTPUT
          echo "::endgroup::"
          exit 1
        fi

        echo "Organization ID: $ORGANIZATION_ID"
        echo "organization-id=$ORGANIZATION_ID" >> $GITHUB_OUTPUT
        echo "success=true" >> $GITHUB_OUTPUT

        echo "::endgroup::"

    # Step 3: Configure internal Docker registry
    - name: Configure Registry
      id: registry
      uses: nextnodesolutions/github-actions/actions/infrastructure/dokploy-registry-setup@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        cookie-jar: ${{ steps.auth.outputs.cookie-jar }}

    # Step 4: Import SSH key
    - name: Import SSH Key
      id: ssh-key
      uses: nextnodesolutions/github-actions/actions/infrastructure/dokploy-ssh-key-import@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        cookie-jar: ${{ steps.auth.outputs.cookie-jar }}
        ssh-private-key: ${{ inputs.dokploy-ssh-private-key }}
        organization-id: ${{ steps.auth.outputs.organization-id }}

    # NOTE: Worker registration removed - unified Swarm architecture
    # Workers now join admin-dokploy's Swarm via infrastructure (NixOS swarm.nix)
    # instead of being registered as separate "Remote Servers" in Dokploy
    # The Swarm node labels (server=hostname) handle placement constraints

    # Step 5: Collect results
    - name: Collect Results
      id: result
      shell: bash
      run: |
        echo "::group::Dokploy Initialization Results"

        echo "Admin setup: ${{ steps.admin-setup.outputs.setup-completed == 'true' && 'completed' || 'skipped (already configured)' }}"
        echo "Registry: ${{ steps.registry.outputs.success == 'true' && 'configured' || 'failed' }}"
        echo "SSH key: ${{ steps.ssh-key.outputs.success == 'true' && 'imported' || 'failed' }}"

        echo ""
        echo "=== Initialization complete ==="
        echo "NOTE: Workers join Swarm via infrastructure (NixOS swarm.nix), not via Dokploy registration"

        echo "success=true" >> $GITHUB_OUTPUT
        echo "initialized-workers=" >> $GITHUB_OUTPUT

        echo "::endgroup::"
