name: 'Dokploy Domain Config'
description: 'Configure domain on Dokploy application'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  app-id:
    description: 'Dokploy application ID'
    required: true
  domain:
    description: 'Domain hostname'
    required: true
  port:
    description: 'Application port'
    required: false
    default: '3000'
  https:
    description: 'Enable HTTPS'
    required: false
    default: 'true'
  certificate-type:
    description: 'Certificate type (letsencrypt, none)'
    required: false
    default: 'letsencrypt'

outputs:
  domain-id:
    description: 'Dokploy domain ID'
    value: ${{ steps.config.outputs.domain-id }}
  configured:
    description: 'Whether domain was configured successfully'
    value: ${{ steps.config.outputs.configured }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.config.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: nextnodesolutions/github-actions/actions/utilities/python-setup@main
      with:
        packages: 'requests'

    - name: Configure domain
      id: config
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-token }}
        APP_ID: ${{ inputs.app-id }}
        DOMAIN: ${{ inputs.domain }}
        PORT: ${{ inputs.port }}
        HTTPS: ${{ inputs.https }}
        CERTIFICATE_TYPE: ${{ inputs.certificate-type }}
      run: |
        import os
        import sys

        from lib.dokploy import DEFAULT_PORT, DokployClient, DokployError, Endpoints, output

        APP_ID = os.environ['APP_ID']
        DOMAIN = os.environ['DOMAIN']
        PORT = int(os.environ.get('PORT', str(DEFAULT_PORT)))
        HTTPS = os.environ.get('HTTPS', 'true').lower() == 'true'
        CERTIFICATE_TYPE = os.environ.get('CERTIFICATE_TYPE', 'letsencrypt')

        print("::group::Configuring domain")
        print(f"Domain: {DOMAIN} (port {PORT})")

        try:
            client = DokployClient.from_env()

            result = client.post(
                Endpoints.DOMAIN_CREATE,
                json={
                    "applicationId": APP_ID,
                    "host": DOMAIN,
                    "port": PORT,
                    "https": HTTPS,
                    "certificateType": CERTIFICATE_TYPE if HTTPS else "none"
                }
            )

            domain_id = result.get('domainId', '')
            print(f"Domain configured: {DOMAIN}")
            output('domain-id', domain_id)
            output('configured', 'true')
            output('success', 'true')

        except DokployError as e:
            print(f"::error::Failed to configure domain: {e}")
            output('domain-id', '')
            output('configured', 'false')
            output('success', 'false')
            sys.exit(1)

        print("::endgroup::")
