# Default configuration for NextNode GitHub Actions
# This file centralizes all default values to follow DRY principle

node:
  version: '20'
  
pnpm:
  version: '10.12.4'
  
audit:
  level: 'high'
  
environment:
  working_directory: '.'
  frozen_lockfile: true
  
railway:
  memory_mb: '512'
  memory_mb_prod: '1024'
  
timeouts:
  health_check_seconds: 30
  deploy_timeout_minutes: 15