# Default configuration for NextNode GitHub Actions
# This file centralizes all default values to follow DRY principle

node:
  version: '20'
  
pnpm:
  version: '10.11.0'
  
audit:
  level: 'high'
  
environment:
  working_directory: '.'
  frozen_lockfile: true