name: 'Dokploy Auth'
description: 'Validate Dokploy API token and pass through for downstream actions'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-api-token:
    description: 'Dokploy API token (from Settings > Profile > API/CLI)'
    required: true

outputs:
  token:
    description: 'Validated API token for Dokploy API'
    value: ${{ steps.auth.outputs.token }}
  success:
    description: 'Whether authentication succeeded'
    value: ${{ steps.auth.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: nextnodesolutions/github-actions/actions/utilities/python-setup@main
      with:
        packages: 'requests'

    - name: Validate Dokploy Token
      id: auth
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_TOKEN: ${{ inputs.dokploy-api-token }}
      run: |
        import os
        import sys

        from lib.dokploy import DokployAuthError, DokployClient, DokployError, output

        print("::group::Validating Dokploy API Token")

        try:
            client = DokployClient.from_env()
            client.verify_token()

            print("API token validated successfully")
            output('token', os.environ['DOKPLOY_TOKEN'])
            output('success', 'true')

        except DokployAuthError as e:
            print("::error::Invalid API token - check Settings > Profile > API/CLI in Dokploy")
            output('success', 'false')
            output('token', '')
            sys.exit(1)

        except DokployError as e:
            print(f"::error::Failed to validate token: {e}")
            output('success', 'false')
            output('token', '')
            sys.exit(1)

        print("::endgroup::")
