name: 'Dokploy Auth'
description: 'Authenticate with Dokploy API and return bearer token'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-admin-email:
    description: 'Dokploy admin email'
    required: true
  dokploy-admin-password:
    description: 'Dokploy admin password'
    required: true

outputs:
  token:
    description: 'Bearer token for Dokploy API'
    value: ${{ steps.auth.outputs.token }}
  success:
    description: 'Whether authentication succeeded'
    value: ${{ steps.auth.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: nextnodesolutions/github-actions/actions/utilities/python-setup@main
      with:
        packages: 'requests'

    - name: Authenticate with Dokploy
      id: auth
      shell: python
      env:
        DOKPLOY_URL: ${{ inputs.dokploy-url }}
        DOKPLOY_ADMIN_EMAIL: ${{ inputs.dokploy-admin-email }}
        DOKPLOY_ADMIN_PASSWORD: ${{ inputs.dokploy-admin-password }}
      run: |
        import os
        import sys

        from lib.dokploy import DokployAuthError, DokployClient, DokployError, output

        DOKPLOY_URL = os.environ['DOKPLOY_URL']
        DOKPLOY_ADMIN_EMAIL = os.environ['DOKPLOY_ADMIN_EMAIL']
        DOKPLOY_ADMIN_PASSWORD = os.environ['DOKPLOY_ADMIN_PASSWORD']

        print("::group::Authenticating with Dokploy")

        try:
            client = DokployClient(url=DOKPLOY_URL, token="")
            token = client.authenticate(DOKPLOY_ADMIN_EMAIL, DOKPLOY_ADMIN_PASSWORD)

            # Verify token works
            client = DokployClient(url=DOKPLOY_URL, token=token)
            client.verify_token()

            print("Authentication successful")
            output('token', token)
            output('success', 'true')

        except DokployAuthError as e:
            print(f"::error::Invalid email or password")
            output('success', 'false')
            output('token', '')
            sys.exit(1)

        except DokployError as e:
            print(f"::error::Failed to authenticate: {e}")
            output('success', 'false')
            output('token', '')
            sys.exit(1)

        print("::endgroup::")
