name: 'Validate Tokens'
description: 'Validates multiple API tokens in parallel (Cloudflare, NPM)'

inputs:
  cloudflare-api-token:
    description: 'Cloudflare API token to validate (optional)'
    required: false
  npm-token:
    description: 'NPM authentication token to validate (optional)'
    required: false
  npm-registry-url:
    description: 'NPM registry URL'
    required: false
    default: 'https://registry.npmjs.org'
  fail-on-invalid:
    description: 'Fail the action if any token is invalid'
    required: false
    default: 'true'

outputs:
  all-valid:
    description: 'Whether all provided tokens are valid (true/false)'
    value: ${{ steps.summary.outputs.all-valid }}
  cloudflare-valid:
    description: 'Cloudflare token validity (true/false/skipped)'
    value: ${{ steps.summary.outputs.cloudflare-valid }}
  npm-valid:
    description: 'NPM token validity (true/false/skipped)'
    value: ${{ steps.summary.outputs.npm-valid }}
  validation-summary:
    description: 'JSON object with detailed validation results'
    value: ${{ steps.summary.outputs.validation-summary }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
      with:
        repository: NextNodeSolutions/github-actions
        token: ${{ github.token }}
        path: .github-actions-validation

    - name: Validate Cloudflare Token
      id: cloudflare
      if: inputs.cloudflare-api-token != ''
      uses: ./.github-actions-validation/actions/utilities/validate-cloudflare-token
      with:
        cloudflare-api-token: ${{ inputs.cloudflare-api-token }}
        fail-on-invalid: 'false'
      continue-on-error: true

    - name: Validate NPM Token
      id: npm
      if: inputs.npm-token != ''
      uses: ./.github-actions-validation/actions/utilities/validate-npm-token
      with:
        npm-token: ${{ inputs.npm-token }}
        registry-url: ${{ inputs.npm-registry-url }}
        fail-on-invalid: 'false'
      continue-on-error: true

    - name: Validation Summary
      id: summary
      shell: bash
      env:
        CF_PROVIDED: ${{ inputs.cloudflare-api-token != '' }}
        CF_VALID: ${{ steps.cloudflare.outputs.is-valid }}
        CF_STATUS: ${{ steps.cloudflare.outputs.status }}
        CF_ERROR: ${{ steps.cloudflare.outputs.error-message }}

        NPM_PROVIDED: ${{ inputs.npm-token != '' }}
        NPM_VALID: ${{ steps.npm.outputs.is-valid }}
        NPM_ERROR: ${{ steps.npm.outputs.error-message }}

        FAIL_ON_INVALID: ${{ inputs.fail-on-invalid }}
      run: |
        echo "::group::Token Validation Summary"
        echo ""

        # Determine individual validation results
        if [[ "$CF_PROVIDED" == "true" ]]; then
          CF_RESULT="${CF_VALID:-false}"
        else
          CF_RESULT="skipped"
        fi

        if [[ "$NPM_PROVIDED" == "true" ]]; then
          NPM_RESULT="${NPM_VALID:-false}"
        else
          NPM_RESULT="skipped"
        fi

        # Display results table
        echo "| Service | Status | Details |"
        echo "|---------|--------|---------|"

        if [[ "$CF_RESULT" == "true" ]]; then
          echo "| Cloudflare | Valid | Status: $CF_STATUS |"
        elif [[ "$CF_RESULT" == "false" ]]; then
          echo "| Cloudflare | Invalid | $CF_ERROR |"
        else
          echo "| Cloudflare | Skipped | Not provided |"
        fi

        if [[ "$NPM_RESULT" == "true" ]]; then
          echo "| NPM | Valid | Authenticated |"
        elif [[ "$NPM_RESULT" == "false" ]]; then
          echo "| NPM | Invalid | $NPM_ERROR |"
        else
          echo "| NPM | Skipped | Not provided |"
        fi

        echo ""

        # Determine overall validity
        ALL_VALID="true"
        FAILED_SERVICES=""

        if [[ "$CF_RESULT" == "false" ]]; then
          ALL_VALID="false"
          FAILED_SERVICES="Cloudflare "
        fi

        if [[ "$NPM_RESULT" == "false" ]]; then
          ALL_VALID="false"
          FAILED_SERVICES="${FAILED_SERVICES}NPM "
        fi

        # Create JSON summary
        VALIDATION_JSON=$(cat <<EOF
        {
          "all_valid": $ALL_VALID,
          "cloudflare": {
            "valid": "$CF_RESULT",
            "status": "${CF_STATUS:-}",
            "error": "${CF_ERROR:-}"
          },
          "npm": {
            "valid": "$NPM_RESULT",
            "error": "${NPM_ERROR:-}"
          }
        }
        EOF
        )

        # Set outputs
        echo "all-valid=$ALL_VALID" >> $GITHUB_OUTPUT
        echo "cloudflare-valid=$CF_RESULT" >> $GITHUB_OUTPUT
        echo "npm-valid=$NPM_RESULT" >> $GITHUB_OUTPUT
        echo "validation-summary<<EOF" >> $GITHUB_OUTPUT
        echo "$VALIDATION_JSON" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        if [[ "$ALL_VALID" == "true" ]]; then
          echo "All provided tokens are valid!"
        else
          echo "Token validation failed for: $FAILED_SERVICES"
        fi

        echo "::endgroup::"

        # Fail if requested and any token is invalid
        if [[ "$ALL_VALID" == "false" && "$FAIL_ON_INVALID" == "true" ]]; then
          echo ""
          echo "::error::Token validation failed for: $FAILED_SERVICES"
          exit 1
        fi
