name: 'Quality Pipeline'
description: 'Run comprehensive quality checks: lint, type-check, test, and build'
inputs:
  working-directory:
    description: 'Working directory to run commands in'
    required: false
    default: '.'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  pnpm-version:
    description: 'PNPM version to use'
    required: false
    default: '10.11.0'
  skip-tests:
    description: 'Skip running tests'
    required: false
    default: 'false'
  skip-build:
    description: 'Skip running build'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install --frozen-lockfile

    - name: Run Lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm lint

    - name: Run Type Check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm type-check

    - name: Run Tests
      if: inputs.skip-tests != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm test

    - name: Run Build
      if: inputs.skip-build != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm build