name: 'Setup Node.js'
description: 'Setup Node.js with caching support'
inputs:
  node-version:
    description: 'Node.js version to setup'
    required: false
    default: '22'
  cache:
    description: 'Package manager to cache'
    required: false
    default: 'pnpm'
  cache-dependency-path:
    description: 'Path to dependency file for cache key'
    required: false
    default: 'pnpm-lock.yaml'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}