# Optimized CI/CD template for TypeScript libraries
# Copy this to your repository's .github/workflows/ directory

name: CI/CD

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main]
  workflow_dispatch:

# Prevent concurrent releases
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Single job for all quality checks (faster than parallel jobs for small projects)
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: NextNodeSolutions/github-actions
          path: .github-actions
          sparse-checkout: actions
      - uses: ./.github-actions/actions/quality-pipeline
  
  # Combined quality + release for main branch
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
      packages: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/checkout@v4
        with:
          repository: NextNodeSolutions/github-actions  
          path: .github-actions
          sparse-checkout: actions
          
      - uses: ./.github-actions/actions/quality-pipeline
      
      - uses: changesets/action@v1
        with:
          publish: pnpm changeset:publish
          version: pnpm changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0