name: 'Dokploy App Sync'
description: 'Create or update Dokploy application (composes atomic actions)'
author: 'NextNodeSolutions'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  dokploy-token:
    description: 'Dokploy bearer token'
    required: true
  project-id:
    description: 'Dokploy project ID'
    required: true
  environment-id:
    description: 'Dokploy environment ID'
    required: true
  app-name:
    description: 'Application name'
    required: true
  server-id:
    description: 'Dokploy server ID'
    required: false
    default: ''
  docker-image:
    description: 'Docker image to deploy'
    required: false
    default: ''
  github-url:
    description: 'GitHub repository URL (alternative to docker-image)'
    required: false
    default: ''
  domain:
    description: 'Domain for the application'
    required: false
    default: ''
  port:
    description: 'Application port'
    required: false
    default: '3000'
  build-type:
    description: 'Build type (dockerfile, nixpacks, etc.)'
    required: false
    default: 'dockerfile'
  healthcheck-path:
    description: 'Health check path'
    required: false
    default: '/health'
  healthcheck-interval:
    description: 'Health check interval in seconds'
    required: false
    default: '30'
  healthcheck-timeout:
    description: 'Health check timeout in seconds'
    required: false
    default: '10'
  healthcheck-retries:
    description: 'Health check retries'
    required: false
    default: '3'
  healthcheck-start-period:
    description: 'Health check start period in seconds'
    required: false
    default: '40'
  rollback-on-failure:
    description: 'Auto-rollback on failure'
    required: false
    default: 'true'
  skip-deploy:
    description: 'Skip deployment trigger'
    required: false
    default: 'false'

outputs:
  application-id:
    description: 'Dokploy application ID'
    value: ${{ steps.app-create.outputs.app-id }}
  created:
    description: 'Whether application was created'
    value: ${{ steps.app-create.outputs.created }}
  deployment-id:
    description: 'Deployment ID (if triggered)'
    value: ${{ steps.deploy.outputs.deployment-id }}
  success:
    description: 'Whether operation succeeded'
    value: ${{ steps.app-create.outputs.success }}

runs:
  using: 'composite'
  steps:
    # Step 1: Create or find application
    - name: Create or find application
      id: app-create
      uses: nextnodesolutions/github-actions/actions/app/dokploy-app-create@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        dokploy-token: ${{ inputs.dokploy-token }}
        project-id: ${{ inputs.project-id }}
        environment-id: ${{ inputs.environment-id }}
        app-name: ${{ inputs.app-name }}
        server-id: ${{ inputs.server-id }}
        build-type: ${{ inputs.build-type }}

    # Step 2: Configure source (Docker or GitHub)
    - name: Configure Docker source
      if: inputs.docker-image != ''
      uses: nextnodesolutions/github-actions/actions/app/dokploy-source-config@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        dokploy-token: ${{ inputs.dokploy-token }}
        app-id: ${{ steps.app-create.outputs.app-id }}
        source-type: docker
        docker-image: ${{ inputs.docker-image }}

    - name: Configure GitHub source
      if: inputs.docker-image == '' && inputs.github-url != ''
      uses: nextnodesolutions/github-actions/actions/app/dokploy-source-config@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        dokploy-token: ${{ inputs.dokploy-token }}
        app-id: ${{ steps.app-create.outputs.app-id }}
        source-type: github
        github-url: ${{ inputs.github-url }}

    # Step 3: Configure domain (if provided)
    - name: Configure domain
      if: inputs.domain != ''
      uses: nextnodesolutions/github-actions/actions/app/dokploy-domain-config@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        dokploy-token: ${{ inputs.dokploy-token }}
        app-id: ${{ steps.app-create.outputs.app-id }}
        domain: ${{ inputs.domain }}
        port: ${{ inputs.port }}

    # Step 4: Configure health check
    - name: Configure health check
      uses: nextnodesolutions/github-actions/actions/app/dokploy-health-config@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        dokploy-token: ${{ inputs.dokploy-token }}
        app-id: ${{ steps.app-create.outputs.app-id }}
        port: ${{ inputs.port }}
        health-path: ${{ inputs.healthcheck-path }}
        health-interval: ${{ inputs.healthcheck-interval }}
        health-timeout: ${{ inputs.healthcheck-timeout }}
        health-retries: ${{ inputs.healthcheck-retries }}
        health-start-period: ${{ inputs.healthcheck-start-period }}
        rollback-on-failure: ${{ inputs.rollback-on-failure }}

    # Step 5: Trigger deployment
    - name: Trigger deployment
      id: deploy
      if: inputs.skip-deploy != 'true'
      uses: nextnodesolutions/github-actions/actions/app/dokploy-deploy-trigger@main
      with:
        dokploy-url: ${{ inputs.dokploy-url }}
        dokploy-token: ${{ inputs.dokploy-token }}
        app-id: ${{ steps.app-create.outputs.app-id }}
