name: 'Cloudflare Headers Setup'
description: 'Configure security and SEO headers via Cloudflare Transform Rules'

inputs:
  cloudflare-api-token:
    description: 'Cloudflare API token with Zone:Edit permissions'
    required: true
  cloudflare-zone-id:
    description: 'Cloudflare Zone ID (auto-detected if not provided)'
    required: false
  domain:
    description: 'Domain for zone lookup if zone-id not provided'
    required: true
  headers:
    description: 'JSON object of headers to set (e.g., {"X-Frame-Options": "DENY"})'
    required: true
  expression:
    description: 'Cloudflare expression for when to apply headers (default: all requests)'
    required: false
    default: 'true'
  dry-run:
    description: 'Show what would be configured without making changes'
    required: false
    default: 'false'

outputs:
  configured:
    description: 'Whether the headers configuration was successful'
    value: ${{ steps.headers-setup.outputs.configured }}
  rule-id:
    description: 'The Transform Rules ruleset ID'
    value: ${{ steps.headers-setup.outputs.rule-id }}

runs:
  using: 'composite'
  steps:
    - name: Lookup Cloudflare Zone
      id: zone-lookup
      if: ${{ inputs.cloudflare-zone-id == '' }}
      uses: nextnodesolutions/github-actions/actions/utilities/cloudflare-zone-lookup@main
      with:
        domain: ${{ inputs.domain }}
        cloudflare-api-token: ${{ inputs.cloudflare-api-token }}

    - name: Configure Headers via Transform Rules
      id: headers-setup
      shell: bash
      env:
        CF_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        CF_ZONE_ID: ${{ inputs.cloudflare-zone-id || steps.zone-lookup.outputs.zone-id }}
        DOMAIN: ${{ inputs.domain }}
        HEADERS_JSON: ${{ inputs.headers }}
        EXPRESSION: ${{ inputs.expression }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        echo "::group::Cloudflare Headers Setup"

        # Validate inputs
        if [[ -z "$CF_API_TOKEN" ]]; then
          echo "::error::Cloudflare API token is required"
          exit 1
        fi

        if [[ -z "$CF_ZONE_ID" ]]; then
          echo "::error::Could not determine Zone ID"
          exit 1
        fi

        if [[ -z "$HEADERS_JSON" ]]; then
          echo "::error::Headers JSON is required"
          exit 1
        fi

        echo "Configuration:"
        echo "  Domain: $DOMAIN"
        echo "  Zone ID: $CF_ZONE_ID"
        echo "  Expression: $EXPRESSION"
        echo "  Headers: $HEADERS_JSON"
        echo "  Dry run: $DRY_RUN"
        echo ""

        # Get or create Transform Rules ruleset
        RULESET_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/rulesets" \
          -H "Authorization: Bearer $CF_API_TOKEN" \
          -H "Content-Type: application/json")

        API_SUCCESS=$(echo "$RULESET_RESPONSE" | jq -r '.success // false')
        if [[ "$API_SUCCESS" != "true" ]]; then
          echo "::error::Failed to get rulesets from Cloudflare API"
          echo "configured=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        RULESET_ID=$(echo "$RULESET_RESPONSE" | jq -r '.result // [] | .[] | select(.phase == "http_response_headers_transform") | .id // empty')

        if [[ -z "$RULESET_ID" ]]; then
          echo "Creating new http_response_headers_transform ruleset..."

          if [[ "$DRY_RUN" == "true" ]]; then
            echo "  [DRY RUN] Would create ruleset"
            echo "configured=true" >> $GITHUB_OUTPUT
            echo "::endgroup::"
            exit 0
          fi

          CREATE_RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/rulesets" \
            -H "Authorization: Bearer $CF_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{
              "name": "Generated ruleset",
              "description": "Custom headers ruleset",
              "kind": "zone",
              "phase": "http_response_headers_transform"
            }')

          RULESET_ID=$(echo "$CREATE_RESPONSE" | jq -r '.result.id // empty')

          if [[ -z "$RULESET_ID" ]]; then
            echo "::error::Failed to create ruleset"
            echo "configured=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "Created ruleset: $RULESET_ID"
        else
          echo "Found existing ruleset: $RULESET_ID"
        fi

        echo "rule-id=$RULESET_ID" >> $GITHUB_OUTPUT

        if [[ "$DRY_RUN" == "true" ]]; then
          echo "[DRY RUN] Would add headers rule"
          echo "configured=true" >> $GITHUB_OUTPUT
          echo "::endgroup::"
          exit 0
        fi

        # Get existing rules
        EXISTING_RULESET=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/rulesets/$RULESET_ID" \
          -H "Authorization: Bearer $CF_API_TOKEN" \
          -H "Content-Type: application/json")

        EXISTING_RULES=$(echo "$EXISTING_RULESET" | jq -r '.result.rules // []')

        # Build headers object for action_parameters
        HEADERS_OBJ=$(echo "$HEADERS_JSON" | jq 'to_entries | map({(.key): {operation: "set", value: .value}}) | add')

        # Create new rule
        NEW_RULE=$(jq -n \
          --arg expression "$EXPRESSION" \
          --argjson headers "$HEADERS_OBJ" \
          '{
            action: "rewrite",
            expression: $expression,
            description: "Custom headers rule",
            action_parameters: {
              headers: $headers
            }
          }')

        RULES_JSON=$(echo "$EXISTING_RULES" | jq --argjson rule "$NEW_RULE" '. + [$rule]')

        # Update ruleset
        UPDATE_RESPONSE=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/rulesets/$RULESET_ID" \
          -H "Authorization: Bearer $CF_API_TOKEN" \
          -H "Content-Type: application/json" \
          --data "$(jq -n --argjson rules "$RULES_JSON" '{rules: $rules}')")

        UPDATE_SUCCESS=$(echo "$UPDATE_RESPONSE" | jq -r '.success // false')

        if [[ "$UPDATE_SUCCESS" == "true" ]]; then
          echo "Headers configured successfully"
          echo "configured=true" >> $GITHUB_OUTPUT
        else
          echo "::error::Failed to update Transform Rules"
          echo "$UPDATE_RESPONSE" | jq '.errors[]?' 2>/dev/null
          echo "configured=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        echo "::endgroup::"
