name: Lint Job

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        default: '22'
        type: string
      pnpm-version:
        description: 'pnpm version'
        required: false
        default: '10.11.0'
        type: string
      working-directory:
        description: 'Working directory'
        required: false
        default: '.'
        type: string
      command:
        description: 'Lint command to run'
        required: false
        default: 'pnpm lint'
        type: string

jobs:
  lint:
    name: '🔍 Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: NextNodeSolutions/github-actions/actions/setup-environment@main
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}
          working-directory: ${{ inputs.working-directory }}
          
      - name: Run linting
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.command }}