name: Quality Full

# EXTERNAL WORKFLOW - Quality checks orchestrator
# Calls individual quality check workflows in parallel

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory'
        required: false
        default: '.'
        type: string
      # Individual check toggles
      run-lint:
        description: 'Run linting'
        required: false
        default: true
        type: boolean
      run-typecheck:
        description: 'Run type checking'
        required: false
        default: true
        type: boolean
      run-tests:
        description: 'Run tests'
        required: false
        default: true
        type: boolean
      run-build:
        description: 'Run build'
        required: false
        default: true
        type: boolean
      run-security:
        description: 'Run security audit'
        required: false
        default: false
        type: boolean
      # Test configuration
      test-coverage:
        description: 'Enable test coverage'
        required: false
        default: false
        type: boolean
      coverage-threshold:
        description: 'Coverage threshold percentage'
        required: false
        default: '80'
        type: string
      # Lint configuration
      lint-fix:
        description: 'Auto-fix lint issues'
        required: false
        default: false
        type: boolean
      fail-on-warning:
        description: 'Fail on warnings'
        required: false
        default: false
        type: boolean
      # Build configuration
      build-command:
        description: 'Build command'
        required: false
        default: 'build'
        type: string
      output-directory:
        description: 'Build output directory'
        required: false
        default: 'dist'
        type: string
      # Security configuration
      audit-level:
        description: 'Security audit level'
        required: false
        default: 'high'
        type: string
    outputs:
      all-passed:
        description: 'Whether all enabled checks passed'
        value: ${{ jobs.summary.outputs.all-passed }}

jobs:
  lint:
    name: Lint
    if: inputs.run-lint
    uses: ./.github/workflows/lint.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      lint-fix: ${{ inputs.lint-fix }}
      fail-on-warning: ${{ inputs.fail-on-warning }}

  typecheck:
    name: Type Check
    if: inputs.run-typecheck
    uses: ./.github/workflows/typecheck.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      strict: true

  test:
    name: Test
    if: inputs.run-tests
    uses: ./.github/workflows/test.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      coverage: ${{ inputs.test-coverage }}
      coverage-threshold: ${{ inputs.coverage-threshold }}
      upload-coverage: ${{ inputs.test-coverage }}

  build:
    name: Build
    if: inputs.run-build
    uses: ./.github/workflows/build.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      build-command: ${{ inputs.build-command }}
      output-directory: ${{ inputs.output-directory }}

  security:
    name: Security
    if: inputs.run-security
    uses: ./.github/workflows/security.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      audit-level: ${{ inputs.audit-level }}

  summary:
    name: Quality Summary
    needs: [lint, typecheck, test, build, security]
    if: always()
    runs-on: ubuntu-latest
    outputs:
      all-passed: ${{ steps.check.outputs.all-passed }}
    steps:
      - name: Check all job results
        uses: NextNodeSolutions/github-actions/actions/monitoring/check-job-results@main
        id: check
        with:
          job-results: |
            [
              "${{ needs.lint.result }}",
              "${{ needs.typecheck.result }}",
              "${{ needs.test.result }}",
              "${{ needs.build.result }}",
              "${{ needs.security.result }}"
            ]
          fail-on-error: true