name: Railway Deploy

# EXTERNAL WORKFLOW - Atomic Railway deployment workflow
# Deploys to Railway platform only

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment (development/staging/production)'
        required: true
        type: string
      app-name:
        description: 'Application name for Railway project'
        required: true
        type: string
      working-directory:
        description: 'Working directory'
        required: false
        default: '.'
        type: string
      memory-mb:
        description: 'Memory allocation in MB'
        required: false
        default: '512'
        type: string
      variables:
        description: 'Environment variables as JSON object'
        required: false
        default: '{}'
        type: string
      wait-for-deployment:
        description: 'Wait for deployment to complete'
        required: false
        default: true
        type: boolean
      timeout-seconds:
        description: 'Deployment timeout in seconds'
        required: false
        default: '300'
        type: string
    secrets:
      RAILWAY_API_TOKEN:
        required: true
    outputs:
      deployment-id:
        description: 'Railway deployment ID'
        value: ${{ jobs.deploy.outputs.deployment-id }}
      railway-url:
        description: 'Railway internal URL'
        value: ${{ jobs.deploy.outputs.railway-url }}
      deployment-status:
        description: 'Deployment status'
        value: ${{ jobs.deploy.outputs.status }}

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    outputs:
      deployment-id: ${{ steps.railway.outputs.deployment-id }}
      railway-url: ${{ steps.railway.outputs.railway-url }}
      status: ${{ steps.railway.outputs.status }}
    steps:
      - uses: actions/checkout@v4
        
      - id: railway
        uses: ./actions/railway-deploy
        with:
          environment: ${{ inputs.environment }}
          app-name: ${{ inputs.app-name }}
          memory-mb: ${{ inputs.memory-mb }}
          variables: ${{ inputs.variables }}
          wait-for-deployment: ${{ inputs.wait-for-deployment }}
          timeout-seconds: ${{ inputs.timeout-seconds }}
          railway-token: ${{ secrets.RAILWAY_API_TOKEN }}