name: Type Check

# EXTERNAL WORKFLOW - Atomic type checking workflow
# Performs TypeScript type checking only

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory'
        required: false
        default: '.'
        type: string
      strict:
        description: 'Enable strict type checking'
        required: false
        default: true
        type: boolean
    outputs:
      typecheck-passed:
        description: 'Whether type checking passed'
        value: ${{ jobs.typecheck.outputs.passed }}

jobs:
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ steps.typecheck.outcome == 'success' }}
    steps:
      - uses: NextNodeSolutions/github-actions/actions/node-setup-complete@main
        with:
          working-directory: ${{ inputs.working-directory }}
          
      - id: typecheck
        uses: NextNodeSolutions/github-actions/actions/quality/typecheck@main
        with:
          working-directory: ${{ inputs.working-directory }}
          strict: ${{ inputs.strict }}