name: 'Cloudflare SEO Setup'
description: 'Automated SEO configuration for Cloudflare - blocks dev subdomains, adds redirections, enables optimizations. Composes atomic SEO actions.'

inputs:
  domain:
    description: 'Primary domain (e.g., nextnode.fr)'
    required: true
  blocked-subdomains:
    description: 'Comma-separated list of subdomains to block from search engines'
    required: false
    default: 'dev,staging,test,preview'
  allowed-subdomains:
    description: 'Comma-separated list of subdomains to ALWAYS allow (whitelist)'
    required: false
    default: ''
  cloudflare-api-token:
    description: 'Cloudflare API token with Zone:Edit permissions'
    required: true
  cloudflare-zone-id:
    description: 'Cloudflare Zone ID (auto-detected if not provided)'
    required: false
  enable-www-redirect:
    description: 'Create www -> non-www redirect'
    required: false
    default: 'true'
  enable-optimizations:
    description: 'Enable Cloudflare performance optimizations'
    required: false
    default: 'true'
  dry-run:
    description: 'Show what would be configured without making changes'
    required: false
    default: 'false'

outputs:
  seo-configured:
    description: 'Whether SEO configuration was successful'
    value: ${{ steps.summary.outputs.success }}
  transform-rules-created:
    description: 'Number of transform rules created for SEO blocking'
    value: ${{ steps.robots.outputs.rules-created }}
  redirects-created:
    description: 'Number of redirect rules created'
    value: ${{ steps.redirects.outputs.redirects-count }}
  zone-id:
    description: 'Cloudflare Zone ID (for reuse in subsequent steps)'
    value: ${{ steps.zone-lookup.outputs.zone-id || inputs.cloudflare-zone-id }}

runs:
  using: 'composite'
  steps:
    - name: Lookup Cloudflare Zone
      id: zone-lookup
      if: ${{ inputs.cloudflare-zone-id == '' }}
      uses: nextnodesolutions/github-actions/actions/utilities/cloudflare-zone-lookup@main
      with:
        domain: ${{ inputs.domain }}
        cloudflare-api-token: ${{ inputs.cloudflare-api-token }}

    - name: Configure Robots (X-Robots-Tag)
      id: robots
      uses: nextnodesolutions/github-actions/actions/seo/cloudflare-robots-setup@main
      with:
        cloudflare-api-token: ${{ inputs.cloudflare-api-token }}
        cloudflare-zone-id: ${{ inputs.cloudflare-zone-id || steps.zone-lookup.outputs.zone-id }}
        domain: ${{ inputs.domain }}
        blocked-subdomains: ${{ inputs.blocked-subdomains }}
        allowed-subdomains: ${{ inputs.allowed-subdomains }}
        dry-run: ${{ inputs.dry-run }}

    - name: Configure Redirects
      id: redirects
      uses: nextnodesolutions/github-actions/actions/seo/cloudflare-redirects-setup@main
      with:
        cloudflare-api-token: ${{ inputs.cloudflare-api-token }}
        cloudflare-zone-id: ${{ inputs.cloudflare-zone-id || steps.zone-lookup.outputs.zone-id }}
        domain: ${{ inputs.domain }}
        enable-www-redirect: ${{ inputs.enable-www-redirect }}
        dry-run: ${{ inputs.dry-run }}

    - name: Configure Optimizations
      id: optimizations
      if: ${{ inputs.enable-optimizations == 'true' }}
      uses: nextnodesolutions/github-actions/actions/seo/cloudflare-optimizations-setup@main
      with:
        cloudflare-api-token: ${{ inputs.cloudflare-api-token }}
        cloudflare-zone-id: ${{ inputs.cloudflare-zone-id || steps.zone-lookup.outputs.zone-id }}
        domain: ${{ inputs.domain }}
        enable-minify: 'true'
        enable-brotli: 'true'
        enable-https: 'true'
        security-level: 'medium'
        dry-run: ${{ inputs.dry-run }}

    - name: Summary
      id: summary
      shell: bash
      env:
        ROBOTS_CONFIGURED: ${{ steps.robots.outputs.configured }}
        ROBOTS_RULES: ${{ steps.robots.outputs.rules-created }}
        REDIRECTS_CONFIGURED: ${{ steps.redirects.outputs.configured }}
        REDIRECTS_COUNT: ${{ steps.redirects.outputs.redirects-count }}
        OPTIMIZATIONS_CONFIGURED: ${{ steps.optimizations.outputs.configured }}
        ENABLE_OPTIMIZATIONS: ${{ inputs.enable-optimizations }}
        DOMAIN: ${{ inputs.domain }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        echo "::group::SEO Configuration Summary"

        echo ""
        echo "Domain: $DOMAIN"
        echo "Dry run: $DRY_RUN"
        echo ""
        echo "Results:"
        echo "  - Robots (X-Robots-Tag): $ROBOTS_CONFIGURED (rules created: ${ROBOTS_RULES:-0})"
        echo "  - Redirects: $REDIRECTS_CONFIGURED (count: ${REDIRECTS_COUNT:-0})"
        if [[ "$ENABLE_OPTIMIZATIONS" == "true" ]]; then
          echo "  - Optimizations: $OPTIMIZATIONS_CONFIGURED"
        else
          echo "  - Optimizations: skipped (disabled)"
        fi
        echo ""

        # Determine overall success
        SUCCESS=true
        if [[ "$ROBOTS_CONFIGURED" != "true" ]]; then
          SUCCESS=false
        fi
        if [[ "$REDIRECTS_CONFIGURED" != "true" ]]; then
          SUCCESS=false
        fi
        if [[ "$ENABLE_OPTIMIZATIONS" == "true" && "$OPTIMIZATIONS_CONFIGURED" != "true" ]]; then
          SUCCESS=false
        fi

        echo "Overall success: $SUCCESS"
        echo "success=$SUCCESS" >> $GITHUB_OUTPUT

        echo "::endgroup::"

        if [[ "$SUCCESS" != "true" ]]; then
          echo "::error::Some SEO configurations failed"
          exit 1
        fi
